{
 "title": "Ventilatore",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "air_temperature{sensor=\"inside\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "air_humidity{sensor=\"inside\"}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "atmospheric_pressure{sensor=\"inside\"}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "air_humidity", "legendFormat": "{{sensor}}" },
    { "expr": "fan_running", "legendFormat": "fan running" }
   ]
  },
  {
   "title": "Humidity difference",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "air_humidity{sensor=\"inside\"} - ignoring(sensor, name) air_humidity{sensor=\"outside\"}",
     "legendFormat": "Humidity difference"
    },
    { "expr": "humidity_difference_threshold", "legendFormat": "{{threshold}}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "air_temperature{job=\"ventilatore\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "air_temperature{sensor=\"inside\"} - air_temperature{sensor=\"outside\"}",
     "legendFormat": "temperature difference"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "atmospheric_pressure", "legendFormat": "{{sensor}}" }
   ]
  }
 ]
}